### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by haruelrovix** [miladr0/steve-chat-bot#2]
Hi @miladr0 ! I'm Havit, Director of Engineering at AdaKerja. 

Thanks for the submission. The repo is amazing! 👍 

However, something is not as specified in the requirement.

> the bot should accept both user text answer („yes", „yeah", „yup”, "no”, "nah", etc.)
and **quick reply buttons**.

<img src='https://github.com/miladr0/steve-chat-bot/raw/master/demo.gif' />

Question:
- Is there any reason why did you implement Postback instead of Quick Reply?

References for you:
- [Quick Replies](https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies/)
- [Postback Button](https://developers.facebook.com/docs/messenger-platform/reference/buttons/postback/)

Thanks.

**Comment by miladr0** [comment]
@haruelrovix thank you. 
To be honest this is my first touch with Facebook messenger and obviously I didn't read Facebook documentation completely. 
If you give me some time I can implement it instead.

**Comment by haruelrovix** [comment]
@miladr0 OK. Please implement the missing requirement and let us know once you finish 🤝

**Comment by ashwintiwari88** [comment]
@miladr0  also , as you get to know the differences between those quick reply and postback buttons better , would be great to understand your perspectives on which is better to use for tasks use case, and why. 

nice work so far , we look forward.

**Comment by miladr0** [comment]
@haruelrovix @ashwintiwari88 
Ok i fixed it.
